from __future__ import annotations

from typing import Optional

OcrElement = tuple[str, float, tuple[int, int, int, int]]
MonitorInfo = tuple[int, str, bool, tuple[int, int, int, int]]

# Region is (x, y, width, height). x/y are signed to support multi-monitor
# virtual-screen coordinates with negative origins (monitors left/above primary).
Region = tuple[int, int, int, int]

def screenshot(
    region: Optional[Region] = ...,
    monitor_index: Optional[int] = ...,
) -> bytes: ...
def capture_ocr(
    region: Optional[Region] = ...,
    monitor_index: Optional[int] = ...,
) -> list[OcrElement]: ...
def capture_hash(
    region: Optional[Region] = ...,
    monitor_index: Optional[int] = ...,
) -> int: ...
def ocr_from_png_bytes(png_bytes: bytes) -> list[OcrElement]: ...
def list_monitors() -> list[MonitorInfo]: ...
def get_clipboard() -> str: ...
def set_clipboard(text: str) -> None: ...
def get_mouse_position() -> tuple[float, float]: ...
def move_to(x: float, y: float) -> None: ...
def bezier_move(x: float, y: float, duration: float = ...) -> bool: ...
def click(button: str = ...) -> None: ...
def double_click() -> None: ...
def mouse_down(button: str = ...) -> None: ...
def mouse_up(button: str = ...) -> None: ...
def scroll(amount: int, axis: str = ...) -> None: ...
def type_text(text: str, interval: float = ...) -> None: ...
def press_key(key: str) -> None: ...
def key_combo(keys: list[str]) -> None: ...
def init_ocr(det_model_path: str, rec_model_path: str, keys_path: str) -> bool: ...
