"""Action recorder: capture a live session as a replayable script.

Wrap any object with the ``PyNerve`` action API (no import of ``core`` —
duck-typed, so fakes work in tests)::

    import pynerve as nv
    from pynerve.recorder import Recorder

    rec = Recorder(nv._get_nv())
    with rec:
        nv.click("Login")
        nv.type_into("Password", "s3cret")
    rec.export_script("login_flow.py")   # replayable, deterministic script

``replay=False`` (default) passes calls through to the live desktop while
recording. With ``replay=True`` calls are *not* executed (dry replay of the
call list, useful for validating an exported script without side effects —
note ``find_*``/``observe`` still execute so return values stay real).
"""

from __future__ import annotations

import functools
from pathlib import Path
from typing import Any

#: Mutating actions (recorded for replay). Read-only queries execute even in
#: replay mode and are recorded as comments for context.
RECORDED_ACTIONS = (
    "click", "double_click", "right_click", "middle_click", "hover",
    "type_into", "type_text", "press_key", "key_combo", "scroll",
    "scroll_to", "launch", "focus_window", "drag_and_drop",
    "set_clipboard", "click_image", "move_to", "bezier_move",
    "mouse_down", "mouse_up", "drag_to",
)

READ_ONLY_ACTIONS = ("find", "find_all", "observe", "observe_window", "screenshot",
                     "capture_window", "get_position", "get_clipboard", "list_monitors",
                     "find_image", "invalidate_cache", "wait_for")


class Recorder:
    """Record action calls on a target and export them as Python source."""

    def __init__(self, target: Any, replay: bool = False) -> None:
        self.target = target
        self.replay = replay
        self.calls: list[dict[str, Any]] = []
        self._wrapped: dict[str, Any] = {}

    # -- context manager ------------------------------------------------------

    def __enter__(self) -> "Recorder":
        for name in RECORDED_ACTIONS + READ_ONLY_ACTIONS:
            fn = getattr(self.target, name, None)
            if callable(fn):
                self._wrapped[name] = fn
                setattr(self.target, name, self._make_wrapper(name, fn))
        return self

    def __exit__(self, *exc: Any) -> None:
        for name, fn in self._wrapped.items():
            setattr(self.target, name, fn)
        self._wrapped.clear()

    # -- recording --------------------------------------------------------------

    def _make_wrapper(self, name: str, fn: Any) -> Any:
        read_only = name in READ_ONLY_ACTIONS

        @functools.wraps(fn)
        def _wrapper(*args: Any, **kwargs: Any) -> Any:
            entry: dict[str, Any] = {"action": name, "args": list(args),
                                     "kwargs": dict(kwargs)}
            self.calls.append(entry)
            if self.replay and not read_only:
                entry["replayed"] = True
                return True if name not in ("get_clipboard",) else ""
            return fn(*args, **kwargs)

        return _wrapper

    def __len__(self) -> int:
        return len(self.calls)

    def clear(self) -> None:
        """Discard recorded calls."""
        self.calls.clear()

    # -- export -------------------------------------------------------------------

    def to_source(self, alias: str = "nv") -> str:
        """Render recorded calls as a replayable Python script."""
        lines = [
            '"""Replay script generated by dexflow Recorder."""',
            "from __future__ import annotations",
            "",
            "import pynerve as nv",
            "",
            "",
            "def main() -> None:",
        ]
        if not self.calls:
            lines.append("    pass  # nothing recorded")
        for call in self.calls:
            name = call["action"]
            args = ", ".join([repr(a) for a in call["args"]] +
                              [f"{k}={v!r}" for k, v in call["kwargs"].items()])
            if name in READ_ONLY_ACTIONS:
                lines.append(f"    {alias}.{name}({args})  # recorded query")
            else:
                lines.append(f"    {alias}.{name}({args})")
        lines += ["", "", 'if __name__ == "__main__":', "    main()", ""]
        return "\n".join(lines)

    def export_script(self, path: str | Path, alias: str = "nv") -> Path:
        """Write :meth:`to_source` to ``path`` and return it."""
        out = Path(path)
        if out.parent != Path(""):
            out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(self.to_source(alias), encoding="utf-8")
        return out
